-- Seleziono le variabili per i comuni della provincia di Bari
SELECT COMUNE, PERCENTUALE_RD, PRO_CAPITE_RD, PRO_CAPITE_RU
FROM RD_COMUNALE;


-- Calcolo le medie per i valori dei comuni della provincia di Bari
SELECT ROUND(AVG(PERCENTUALE_RD),4) AS MEDIA_PERCENTUALE_RD,
        ROUND(AVG(PRO_CAPITE_RD),2) AS MEDIA_PRO_CAPITE_RD,
        ROUND(AVG(PRO_CAPITE_RU),2) AS MEDIA_PRO_CAPITE_RU
FROM RD_COMUNALE;


-- Seleziono le variabili regionali della Raccolta Differenziata
SELECT REGIONE, PERCENTUALE_RD, PRO_CAPITE_RD, PRO_CAPITE_RU
FROM RD_REGIONALE;


-- Seleziono il numero di laureati o più nelle regioni italiane
SELECT TERRITORIO, TIPO_TITOLO_STUDIO, VALUE AS LAU
FROM RD_TITOLO_STUDIO
WHERE SEXISTAT1 = 9
AND TITOLO_STUDIO = 11
AND ETA1 = 'Y_GE15';


-- Seleziono il numero totale di intervistati per il titolo di studio
SELECT TERRITORIO, VALUE AS TOT
FROM RD_TITOLO_STUDIO
WHERE SEXISTAT1 = 9
AND TITOLO_STUDIO = 99
AND ETA1 = 'Y_GE15';


-- Calcolo la percentuale di laureati sul totale e la inserisco nella tabella
SELECT L.TERRITORIO, L.TIPO_TITOLO_STUDIO, L.VALUE AS LAU, T.TOT,
    ROUND(L.VALUE / T.TOT, 4) AS PERC_LAUREATI
FROM RD_TITOLO_STUDIO L,
    (SELECT TERRITORIO, VALUE AS TOT
    FROM RD_TITOLO_STUDIO
    WHERE SEXISTAT1 = 9
    AND TITOLO_STUDIO = 99
    AND ETA1 = 'Y_GE15') T
WHERE L.SEXISTAT1 = 9
AND L.TITOLO_STUDIO = 11
AND L.ETA1 = 'Y_GE15'
AND L.TERRITORIO = T.TERRITORIO;


-- Seleziono il reddito medio regionale
SELECT TERRITORIO, VALUE AS REDDITO
FROM RD_REDDITO_REGIONALE
WHERE T_D8 = 'REDD_MEDIO_FAM'
AND PRAF = 2
AND RDPR = 9;


-- Join tra Raccolta Differenziata e Reddito
SELECT R.REGIONE, R.PERCENTUALE_RD, S.VALUE AS REDDITO
FROM RD_REGIONALE R, RD_REDDITO_REGIONALE S
WHERE S.T_D8 = 'REDD_MEDIO_FAM'
AND S.PRAF = 2
AND S.RDPR = 9
AND R.REGIONE = S.TERRITORIO;


-- Join tra Raccolta Differenziata e Percentuale laureati
SELECT R.REGIONE, R.PERCENTUALE_RD, LAU.PERC_LAUREATI
FROM RD_REGIONALE R,
    (SELECT L.TERRITORIO, L.TIPO_TITOLO_STUDIO, L.VALUE AS LAU, T.TOT,
    ROUND(L.VALUE / T.TOT, 4) AS PERC_LAUREATI
    FROM RD_TITOLO_STUDIO L,
        (SELECT TERRITORIO, VALUE AS TOT
        FROM RD_TITOLO_STUDIO
        WHERE SEXISTAT1 = 9
        AND TITOLO_STUDIO = 99
        AND ETA1 = 'Y_GE15') T
    WHERE L.SEXISTAT1 = 9
    AND L.TITOLO_STUDIO = 11
    AND L.ETA1 = 'Y_GE15'
    AND L.TERRITORIO = T.TERRITORIO) LAU
WHERE R.REGIONE = LAU.TERRITORIO;


-- Calcolo la percentuale media di racc differenziata regionale
SELECT ROUND(AVG(PERCENTUALE_RD),4) AS MEDIA
FROM RD_REGIONALE;


-- Calcolo la percentuale media di laureati
SELECT ROUND(AVG(PERC_LAUREATI),4) AS MEDIA
FROM (SELECT L.TERRITORIO, L.TIPO_TITOLO_STUDIO, L.VALUE AS LAU, T.TOT,
    ROUND(L.VALUE / T.TOT, 4) AS PERC_LAUREATI
    FROM RD_TITOLO_STUDIO L,
        (SELECT TERRITORIO, VALUE AS TOT
        FROM RD_TITOLO_STUDIO
        WHERE SEXISTAT1 = 9
        AND TITOLO_STUDIO = 99
        AND ETA1 = 'Y_GE15') T
    WHERE L.SEXISTAT1 = 9
    AND L.TITOLO_STUDIO = 11
    AND L.ETA1 = 'Y_GE15'
    AND L.TERRITORIO = T.TERRITORIO) LAU;
    
    
-- Calcolo il reddito medio 
SELECT ROUND(AVG(REDDITO),2) AS MEDIA
FROM (SELECT TERRITORIO, VALUE AS REDDITO
    FROM RD_REDDITO_REGIONALE
    WHERE T_D8 = 'REDD_MEDIO_FAM'
    AND PRAF = 2
    AND RDPR = 9);
    

